import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalContextProvider } from './components/context/Store'
import { StyledEngineProvider } from '@mui/material/styles';

//? Redux
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'App post it',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {apple: '/icon.png'},
  themeColor: '#000000'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=' scrollbar-thin		scrollbar-thumb-sky-500 
    scrollbar-track-sky-300   scrollbar-thumb-rounded-full scrollbar-track-rounded-full '>
       <meta name="theme-color" content="#000000" />
      <body className={inter.className}>
      <GlobalContextProvider>
      <StyledEngineProvider injectFirst>
          {children}
    </StyledEngineProvider>
      </GlobalContextProvider>
      
        </body>
    </html>
  )
}
